# Generated by Django 3.1.3 on 2021-01-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodeo_app', '0005_auto_20201208_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
