# Generated by Django 3.1.2 on 2021-01-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodeo_app', '0006_auto_20210123_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
